rater/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^access/$', views.access, name='access'),
    url(r'^rate/$', views.rate, name='rate'),
    url(r'^finish/$', views.finish, name='finish'),
    url(r'^(?P<segment_id>[0-9]+)/submit_rating/$', views.submit_rating, name='submit_rating'),
]

translation_rater/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rater/', include('rater.urls', namespace="rater")),
    url(r'^$', RedirectView.as_view(url='/rater/')),
]

rater/models.py
from django.db import models


class Rater(models.Model):
    email = models.CharField(max_length=200)
    batch_id = models.IntegerField(default=0)


class Segment(models.Model):
    translation = models.TextField(max_length=2000)
    reference = models.TextField(max_length=2000)
    batch_id = models.IntegerField()


class Rating(models.Model):
    rater = models.ForeignKey(Rater)
    segment = models.ForeignKey(Segment)
    rating = models.IntegerField(default=0)

rater/views.py
import random
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, redirect, render
from dynamic_preferences import global_preferences_registry
from django.core.cache import cache
from .models import Rater, Segment, Rating

global_preferences = global_preferences_registry.manager()


def index(request):
    template = loader.get_template('rater/index.html')
    return HttpResponse(template.render(RequestContext(request)))


def finish(request):
    template = loader.get_template('rater/finish.html')
    return HttpResponse(template.render(RequestContext(request)))


def access(request):
    rater, created = Rater.objects.get_or_create(email=request.POST['email'])
    if created:
        max_raters = int(global_preferences['rater__number_of_raters_per_batch'])
        batch_number = 0
        cache.clear()

        for b in range(1, int(global_preferences['rater__number_of_batches']) + 1):
            batch_number = b
            if Rater.objects.filter(batch_id=b).count() < max_raters:
                break

        rater.batch_id = batch_number
        rater.save()
    response = HttpResponseRedirect(reverse('rater:rate'))
    response.set_cookie('rater_pk', rater.pk)
    return response


def submit_rating(request, segment_id):
    rater = get_object_or_404(Rater, pk=request.COOKIES['rater_pk'])
    Rating.objects.create(rater_id=rater.pk, segment_id=segment_id, rating=request.POST['rating'])
    response = HttpResponseRedirect(reverse('rater:rate'))
    return response


def rate(request):
    rater = get_object_or_404(Rater, pk=request.COOKIES['rater_pk'])
    total_segments = Segment.objects.filter(batch_id=rater.batch_id).count()
    segment_number = Segment.objects.filter(batch_id=rater.batch_id).filter(
        pk__in=Rating.objects.filter(rater_id=rater.pk).values_list('segment_id', flat=True)
    ).count() + 1

    if total_segments > segment_number - 1:
        segment = Segment.objects.filter(batch_id=rater.batch_id).exclude(
            pk__in=Rating.objects.filter(rater_id=rater.pk).values_list('segment_id', flat=True)
        )[0]
    else:
        return HttpResponseRedirect(reverse('rater:finish'))

    template = loader.get_template('rater/rate.html')
    context = RequestContext(request, {
        'total_segments': total_segments,
        'segment_number': segment_number,
        'segment': segment,
        'choices': global_preferences['rater__single_choice_options'].split(';'),
    })
    return HttpResponse(template.render(context))

rater/templates/rater/finish.html
<html>
<head>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'rater/css/rater.css' %}" />
    <title>Translation rating for UPF</title>
</head>

<body>
    <div id="main">
        <h1>All the segments were rated. Thank you!</h1>
    </div>
</body>
</html>

rater/templates/rater/index.html
<html>
<head>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'rater/css/rater.css' %}" />
    <title>Translation rating for UPF</title>
</head>

<body>
    <div id="main">
        <h1>Enter your email to start rating</h1>

        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

        <div id="access">
            <form action="{% url 'rater:access' %}" method="post">
                {% csrf_token %}
                <label for="email">Email</label>
                <input type="email" name="email" id="email" value="" placeholder="email@example.com" />
                <input type="submit" value="Start" />
            </form>
        </div>

        <div id="content">
            <div id="help">
                {% autoescape off %}
                    {{ global_preferences.rater__help_text }}
                {% endautoescape %}
            </div>
        </div>
    </div>
</body>
</html>

rater/templates/rater/rate.html
<html>
    <head>
        <link href="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.1/themes/redmond/jquery-ui.css" rel="stylesheet" />
        <script type='text/javascript' src='https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.2.min.js'> </script>
        <script  type='text/javascript' src='https://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.1/jquery-ui.min.js'></script>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'rater/css/rater.css' %}" />
    </head>
    <body>
        <div id="main">
            <div class="highlight-box">
                <h3>{{ global_preferences.rater__rating_question }}</h3>
            </div>

            <div id="content">
                <div id="reference">Human translation:<br /><br />{{ segment.reference }}</div>

                <div id="translation">Machine translation:<br /><br />{{ segment.translation }}</div>

                {% if global_preferences.rater__rating_scale == 'continuous_scale' %}
                <div id="slider-content">
                    <div id="slider-min-label" class="slider-label">{{ global_preferences.rater__continuous_scale_min_label }}</div>
                    <div id="slider">&nbsp;</div>
                    <div id="slider-max-label" class="slider-label">{{ global_preferences.rater__continuous_scale_max_label }}</div>
                </div>
                {% endif %}

                {% if global_preferences.rater__rating_scale == 'single_choice' %}
                <div id="choice-content">
                    {% for choice in choices %}
                    <input id="choice_{{ choice }}" type="radio" name="choice" value="{{ forloop.counter }}" onclick="$('#rating').val(this.value)">
                    <label for="choice_{{ choice }}">{{ choice }}</label>
                    {% endfor %}
                </div>
                {% endif %}


                <form id="submit_form" action="{% url 'rater:submit_rating' segment.pk %}" method="post">
                    {% csrf_token %}
                    <input id="rating" name="rating" type="hidden" />
                    <label>Translation {{ segment_number }}/{{ total_segments }}</label>
                    {% if segment_number < total_segments %}
                    <input id="submit_next" type="submit" value="Next" />
                    {% endif %}
                    {% if segment_number == total_segments %}
                    <input id="submit_done" type="submit" value="Done" class="green" />
                    {% endif %}
                </form>
            </div>
        </div>

        {% if global_preferences.rater__rating_scale == 'continuous_scale' %}
        <script type='text/javascript'>
            var selectedValue;
            $(function () {
                $('#rating').val(selectedValue);
                var slider = $("#slider").slider({
                    orientation: "horizontal",
                    min: {{ global_preferences.rater__continuous_scale_min }},
                    max: {{ global_preferences.rater__continuous_scale_max }},
                    value: ({{ global_preferences.rater__continuous_scale_max }} + {{global_preferences.rater__continuous_scale_min }})/2,
                    slide: function (event, ui) {
                        $('#rating').val(ui.value);
                        selectedValue = ui.value;
                    }
                });

                $('#slider').width($('#slider-content').width() - $('#slider-min-label').width() - $('#slider-max-label').width() - 30)
            });
        </script>
        {% endif %}

        {% if global_preferences.rater__rating_scale == 'single_choice' %}
        <script type='text/javascript'>
            $('#submit_form').submit(function(event) {
                if (!$.isNumeric($('#rating').val())) {
                    alert('Please choose an answer');
                    return false;
                }
                return true;
            });
        </script>
        {% endif %}
    </body>
</html>